#!/bin/sh

PREFIX="$(basename $(pwd))"

G_PROJECT_ID="$(gcloud config get-value project)"
G_PROJECT_NUMBER="$(gcloud projects describe ${G_PROJECT_ID} --format='value(projectNumber)')"
G_PROJECT_REGION="$(gcloud config get-value compute/region)"

TF_BUCKET="${PREFIX}-terraform-state"

gsutil mb "gs://${TF_BUCKET}/" >/dev/null 2>&1

cat > config.tf <<EOF
terraform {
  backend "gcs" {
    bucket = "${PREFIX}-terraform-state"
    prefix = "terraform/state"
  }
}

locals {
  project        = "${G_PROJECT_ID}"
  region         = "${G_PROJECT_REGION}"
  prefix         = "${PREFIX}"
  project_number = "${G_PROJECT_NUMBER}"
}

provider "google-beta" {
  region = local.region
}

provider "google" {
  region = local.region
}

resource "google_service_account" "terraform" {
  account_id   = "\${local.prefix}-terraform-sa"
  display_name = "\${local.prefix} Terraform"
}

resource "google_project_iam_member" "terraform" {
  project = local.project
  role    = "roles/owner"
  member  = "serviceAccount:\${google_service_account.terraform.email}"
}

output "terraform_sa" {
  value = google_service_account.terraform.email
}
EOF